api = "0.7"

[buildpack]
  description = "A language family buildpack for building Ruby apps"
  homepage = "https://github.com/paketo-buildpacks/ruby"
  id = "paketo-buildpacks/ruby"
  keywords = ["ruby"]
  name = "Paketo Buildpack for Ruby"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/ruby/blob/main/LICENSE"

[metadata]
  include-files = ["buildpack.toml"]

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/mri"
    version = "0.13.1"

  [[order.group]]
    id = "paketo-buildpacks/bundler"
    version = "0.7.22"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/mri"
    version = "0.13.1"

  [[order.group]]
    id = "paketo-buildpacks/bundler"
    version = "0.7.22"
