name: Create or Update Draft Release

on:
  push:
    branches:
    - 1.6.x
  repository_dispatch:
    types: [ version-bump ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the release to cut (e.g. 1.2.3)'
        required: false
  workflow_run:
    workflows: ["Create Version Line"]
    types:
    - completed

concurrency:
  group: release-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # gets full history
        fetch-tags: true
    - name: Get Latest Tag on Branch ${{ github.ref_name }}
      id: latest
      run: |
        # Get the latest tag in the version line
        # If working off main branch, get the latest tag
        # If working off a version line branch (ex. 1.3.x), get the latest tag in the version line (v1.3.*)
        tag_search=""
        if [[ ${{ github.ref_name }} != "main" ]]; then
          # convert version line into tag search: 1.3.x -> v1.3.*
          tag_search=$(echo ${{ github.ref_name }} | awk -F'[.]' '{printf("v%d.%d.*\n", $1, $2)}')
        fi
        version=$(git tag ${tag_search} --sort "version:refname" --merged | tail -n1)
        echo $version
        echo "version=${version}" >> "$GITHUB_OUTPUT"
    - name: Calculate Semver Tag
      if: github.event.inputs.version == ''
      id: semver
      uses: paketo-buildpacks/github-config/actions/tag/calculate-semver@main
      with:
        repo: ${{ github.repository }}
        token: ${{ github.token }}
        ref-name: ${{ github.ref_name }}
        latest-version: ${{ steps.latest.outputs.version }}
    - name: Set Release Tag
      id: tag
      run: |
        tag="${{ github.event.inputs.version }}"
        if [ -z "${tag}" ]; then
          tag="${{ steps.semver.outputs.tag }}"
        fi
        echo "tag=${tag}" >> "$GITHUB_OUTPUT"
    - name: print
      run: |
        echo ${{ github.ref_name }}
        echo ${{ github.event_name }}
        echo "-----"

    #TODO reset branch to main
    - name: Reset Draft Release
      id: reset
      uses: paketo-buildpacks/github-config/actions/release/reset-draft@reset-draft-version-line
      with:
        repo: ${{ github.repository }}
        token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
        version: v${{ steps.tag.outputs.tag }}

    - name: Create Draft Release
      uses: paketo-buildpacks/github-config/actions/release/create@main
      if: ${{ github.event_name != 'workflow_run' || github.ref_name != 'main' }}
      with:
        repo: ${{ github.repository }}
        token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
        tag_name: v${{ steps.tag.outputs.tag }}
        target_commitish: ${{ github.sha }}
        name: v${{ steps.tag.outputs.tag }}
        draft: true

    # Publish release on main when triggered by the Create Version Line Branch workflow
    - name: Create and Publish Release
      uses: paketo-buildpacks/github-config/actions/release/create@main
      if: ${{ github.event_name == 'workflow_run' && github.ref_name == 'main' }}
      with:
        repo: ${{ github.repository }}
        token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
        tag_name: v${{ steps.tag.outputs.tag }}
        target_commitish: ${{ github.sha }}
        name: v${{ steps.tag.outputs.tag }}
        draft: false
